services:
  - type: web
    name: churn-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run telco_churn_dashboard.py --server.port=$PORT --server.enableCORS=false
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
